apiVersion: v1
kind: Service
metadata:
  name: login-app-service
spec:
  selector:
    app: login-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: login-spring-boot
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: login-angular